uio: fix build: export dmabuf symbols
When building UIO as kmod, the build fails with:
```
ERROR: "uio_dmabuf_unmap" [drivers/uio/uio.ko] undefined!
ERROR: "uio_dmabuf_map" [drivers/uio/uio.ko] undefined!
ERROR: "uio_dmabuf_cleanup" [drivers/uio/uio.ko] undefined!
```

This patch fixes that.

Fixes: de2151831d9 ("uio: Add dma-buf import ioctls")
Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com>